# Generated by Django 5.1.6 on 2026-02-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BlogsCategories",
            fields=[
                ("bc_category_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "bc_category_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("bc_slug", models.CharField(max_length=200, unique=True)),
                (
                    "bc_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bc_category_status",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("bc_parent_id", models.IntegerField(blank=True, null=True)),
                ("bc_created_at", models.DateTimeField()),
                ("bc_updated_at", models.DateTimeField()),
                ("bc_sort_order", models.IntegerField()),
            ],
            options={
                "db_table": "blogs_categories",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BlogsComments",
            fields=[
                ("bc_comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("bc_comment", models.TextField(blank=True, null=True)),
                ("bc_created_at", models.DateTimeField()),
                ("bc_status", models.CharField(max_length=8)),
                ("bc_is_deleted", models.IntegerField()),
            ],
            options={
                "db_table": "blogs_comments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BlogsDetails",
            fields=[
                ("bd_blog_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "bd_blog_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bd_slug", models.CharField(max_length=255, unique=True)),
                ("bd_blog_content", models.TextField(blank=True, null=True)),
                ("bd_excerpt", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "bd_featured_image",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("bd_date_added", models.DateField(blank=True, null=True)),
                ("bd_updated_at", models.DateTimeField(blank=True, null=True)),
                ("bd_published_at", models.DateTimeField(blank=True, null=True)),
                ("bd_user_id", models.IntegerField(blank=True, null=True)),
                ("bd_modified_by", models.IntegerField(blank=True, null=True)),
                (
                    "bd_blog_status",
                    models.CharField(blank=True, max_length=9, null=True),
                ),
                ("bd_category_id", models.IntegerField(blank=True, null=True)),
                ("bd_is_deleted", models.IntegerField()),
                ("bd_views", models.IntegerField()),
            ],
            options={
                "db_table": "blogs_details",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BlogsUsers",
            fields=[
                ("bu_user_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "bu_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "bu_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bu_status", models.CharField(blank=True, max_length=8, null=True)),
                ("bu_email", models.CharField(max_length=150, unique=True)),
                ("bu_password_hash", models.CharField(max_length=255)),
                ("bu_role", models.CharField(max_length=6)),
                ("bu_created_at", models.DateTimeField(auto_now_add=True)),
                ("bu_updated_at", models.DateTimeField(auto_now_add=True)),
                ("bu_last_login", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "blogs_users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.PositiveSmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
    ]
