# Generated by Django 5.1.6 on 2026-02-12 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogsLikes",
            fields=[
                ("bl_like_id", models.AutoField(primary_key=True, serialize=False)),
                ("bl_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bl_blog",
                    models.ForeignKey(
                        db_column="bl_blog_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="blog.blogsdetails",
                    ),
                ),
                (
                    "bl_user",
                    models.ForeignKey(
                        db_column="bl_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="blog.blogsusers",
                    ),
                ),
            ],
            options={
                "db_table": "blogs_likes",
                "unique_together": {("bl_blog", "bl_user")},
            },
        ),
    ]
