# Generated by Django 5.1.6 on 2026-02-12 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogslikes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogslikes",
            options={"managed": True},
        ),
    ]
