# Generated by Django 5.1.6 on 2026-02-16 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogslikes_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogsBookmarks",
            fields=[
                ("bb_id", models.AutoField(primary_key=True, serialize=False)),
                ("bb_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bb_blog",
                    models.ForeignKey(
                        db_column="bb_blog_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="blog.blogsdetails",
                    ),
                ),
                (
                    "bb_user",
                    models.ForeignKey(
                        db_column="bb_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="blog.blogsusers",
                    ),
                ),
            ],
            options={
                "db_table": "blogs_bookmarks",
                "unique_together": {("bb_blog", "bb_user")},
            },
        ),
    ]
