# Generated by Django 5.1.6 on 2026-02-16 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blogsbookmarks"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                ("prt_id", models.AutoField(primary_key=True, serialize=False)),
                ("prt_token", models.CharField(max_length=200, unique=True)),
                ("prt_created_at", models.DateTimeField(auto_now_add=True)),
                ("prt_is_used", models.BooleanField(default=False)),
                (
                    "prt_user",
                    models.ForeignKey(
                        db_column="prt_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.blogsusers",
                    ),
                ),
            ],
            options={
                "db_table": "blogs_password_reset_tokens",
            },
        ),
    ]
