# Generated by Django 5.1.6 on 2026-02-17 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_passwordresettoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswordResetToken",
        ),
    ]
