# Generated by Django 5.1.6 on 2026-02-17 08:49

import blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_delete_passwordresettoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                ("prt_id", models.AutoField(primary_key=True, serialize=False)),
                ("prt_token", models.CharField(max_length=100, unique=True)),
                ("prt_created_at", models.DateTimeField(auto_now_add=True)),
                ("prt_is_used", models.BooleanField(default=False)),
                (
                    "prt_expires_at",
                    models.DateTimeField(default=blog.models.default_prt_expiry),
                ),
                (
                    "prt_user",
                    models.ForeignKey(
                        db_column="prt_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to="blog.blogsusers",
                    ),
                ),
            ],
            options={
                "db_table": "password_reset_token",
            },
        ),
    ]
